openapi: 3.0.0
info:
  version: 1.0-rev0
  title: Veeam Backup for AWS public API 1.0 Agents Tags API
  description: The Agents section defines paths and operations for managing recovery tokens used for bare metal recovery.
security:
- Bearer: []
tags:
- name: Tags
paths:
  /api/v1/cloudInfrastructure/tags:
    get:
      tags:
      - Tags
      operationId: Tags
      parameters:
      - name: SearchPattern
        in: query
        required: false
        x-veeam-spec:
          $ref: '#/components/schemas/TagsFilters'
        schema:
          type: string
      - name: Offset
        in: query
        required: false
        x-veeam-spec:
          $ref: '#/components/schemas/TagsFilters'
        schema:
          type: integer
          format: int32
      - name: Limit
        in: query
        required: false
        x-veeam-spec:
          $ref: '#/components/schemas/TagsFilters'
        schema:
          type: integer
          format: int32
      - name: Sort
        in: query
        required: false
        x-veeam-spec:
          $ref: '#/components/schemas/TagsFilters'
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
            enum:
            - keyAsc
            - keyDesc
      - $ref: '#/components/parameters/apiVersionParam'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TagsPage'
            application/json:
              schema:
                $ref: '#/components/schemas/TagsPage'
            text/json:
              schema:
                $ref: '#/components/schemas/TagsPage'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/TagsPage'
        '401':
          description: Unauthorized. The authorization header has been expected but not found (or found but is expired).
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            text/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. The request has been received but could not be completed because of an internal error at the server side.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            text/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/cloudInfrastructure/tags/{tagId}:
    get:
      tags:
      - Tags
      operationId: Tag
      parameters:
      - name: tagId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - $ref: '#/components/parameters/apiVersionParam'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Tag'
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
            text/json:
              schema:
                $ref: '#/components/schemas/Tag'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Tag'
        '401':
          description: Unauthorized. The authorization header has been expected but not found (or found but is expired).
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            text/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found. One or more resources specified in the request could not be found in the specified resource collection.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            text/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. The request has been received but could not be completed because of an internal error at the server side.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            text/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Link:
      required:
      - rel
      - href
      - method
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
        method:
          type: string
          enum:
          - GET
          - POST
          - PUT
          - DELETE
    TagsFilters:
      type: object
      properties:
        searchPattern:
          type: string
        offset:
          type: integer
          format: int32
          minimum: 0
        limit:
          type: integer
          format: int32
          minimum: -1
        sort:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/TagsSortColumns'
    TagsPage:
      required:
      - results
      - totalCount
      type: object
      properties:
        results:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        totalCount:
          format: int32
          type: integer
        _links:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Link'
    TagsSortColumns:
      type: string
      enum:
      - keyAsc
      - keyDesc
    Error:
      description: ''
      required:
      - type
      - title
      - status
      - errorCode
      type: object
      properties:
        type:
          type: string
          format: uri
          description: An URI reference that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g. using HTML).
        title:
          type: string
          description: A short, summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized)
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
        errorCode:
          description: The error code is a string that uniquely identifies an error condition and should be understood by programs that detect and handle errors by type
          enum:
          - AccessDenied
          - ExpiredToken
          - InvalidToken
          - InvalidURI
          - MethodNotAllowed
          - NotFound
          - NotImplemented
          - ServiceUnavailable
          - UnexpectedContent
          - UnknownError
          type: string
        details:
          description: The error message contains a generic description of the error condition in English. It is intended for a human audience
          type: string
        instance:
          description: ID of the object that is involved in the error (or empty)
          type: string
          format: uri
        data:
          type: object
          description: Error payload
          additionalProperties:
            type: object
    Tag:
      required:
      - id
      - key
      - value
      type: object
      properties:
        id:
          format: uuid
          type: string
        key:
          type: string
        value:
          type: string
        _links:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Link'
  parameters:
    apiVersionParam:
      name: x-api-version
      in: header
      required: true
      schema:
        type: string
        default: 1.0-rev0
  securitySchemes:
    Bearer:
      name: Authorization
      in: header
      type: apiKey
      description: Bearer \<JWT\>
