openapi: 3.2.0
info:
  version: 1.0-rev0
  title: Veeam Backup for AWS public API 1.0 Problems API
security:
- Bearer: []
tags:
- name: Problems
paths:
  /api/v1/problems/accessDenied:
    get:
      tags:
      - Problems
      operationId: AccessDenied
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Access denied
      x-summary-source: derived
  /api/v1/problems/noAccessToken:
    get:
      tags:
      - Problems
      operationId: NoAccessToken
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: No access token
      x-summary-source: derived
  /api/v1/problems/invalidAccessToken:
    get:
      tags:
      - Problems
      operationId: InvalidAccessToken
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Invalid access token
      x-summary-source: derived
  /api/v1/problems/expiredAccessToken:
    get:
      tags:
      - Problems
      operationId: ExpiredAccessToken
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Expired access token
      x-summary-source: derived
  /api/v1/problems/resourceNotFound:
    get:
      tags:
      - Problems
      operationId: ResourceNotFound
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Resource not found
      x-summary-source: derived
  /api/v1/problems/validationError:
    get:
      tags:
      - Problems
      operationId: ValidationError
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Validation error
      x-summary-source: derived
  /api/v1/problems/serviceUnavailable:
    get:
      tags:
      - Problems
      operationId: ServiceUnavailable
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Service unavailable
      x-summary-source: derived
  /api/v1/problems/notImplemented:
    get:
      tags:
      - Problems
      operationId: ActionNotImplemented
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Action not implemented
      x-summary-source: derived
  /api/v1/problems/unknownError:
    get:
      tags:
      - Problems
      operationId: UnknownError
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Unknown error
      x-summary-source: derived
  /api/v1/problems/repositoryUsedByPolicy:
    get:
      tags:
      - Problems
      operationId: RepositoryUsedByPolicy
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Repository used by policy
      x-summary-source: derived
  /api/v1/problems/unsupportedApiVersion:
    get:
      tags:
      - Problems
      operationId: UnsupportedApiVersion
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Unsupported api version
      x-summary-source: derived
  /api/v1/problems/apiVersionUnspecified:
    get:
      tags:
      - Problems
      operationId: ApiVersionUnspecified
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Api version unspecified
      x-summary-source: derived
  /api/v1/problems/invalidApiVersion:
    get:
      tags:
      - Problems
      operationId: InvalidApiVersion
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Invalid api version
      x-summary-source: derived
  /api/v1/problems/ambiguousApiVersion:
    get:
      tags:
      - Problems
      operationId: AmbiguousApiVersion
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Ambiguous api version
      x-summary-source: derived
  /api/v1/problems/failedToRemoveUserPolicy:
    get:
      tags:
      - Problems
      operationId: FailedToRemoveUserPolicy
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Failed to remove user policy
      x-summary-source: derived
  /api/v1/problems/policyAlreadyStarted:
    get:
      tags:
      - Problems
      operationId: PolicyAlreadyStarted
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: Policy already started
      x-summary-source: derived
  /api/v1/problems/licenseAgreementsIsNotAccepted:
    get:
      tags:
      - Problems
      operationId: LicenseAgreementsIsNotAccepted
      responses:
        '200':
          description: Success
          content:
            text/html:
              schema:
                type: string
                format: binary
      security: []
      summary: License agreements is not accepted
      x-summary-source: derived
components:
  securitySchemes:
    Bearer:
      name: Authorization
      in: header
      type: apiKey
      description: Bearer \<JWT\>
